### ISSUE TITLE
Menu improvement

### ISSUE THREAD

**Issue by vdelcoigne** [CosmiCloud/Cosmic_OverlayV2#2]
If the overlay returns to the main menu after executing a command it could be useful. And add a "[0] - Exit" for example in the main menu.

**Comment by calr0x** [comment]
A return to previous menu option would be interesting as well!

**Comment by CosmiCloud** [comment]
Thanks for the suggestion. I have tipped the creator of this issue 1 bat :)

**Comment by CosmiCloud** [comment]
Closing. Feature was implemented in latest update.
